[package]
name = "dedsol-gql-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql_client = { version = "0.14.0" }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.209" }
serde_json = { version = "1.0.127" }
